server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gère le routage de la SPA : renvoie index.html si le fichier n'est pas trouvé
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Mise en cache optionnelle mais recommandée pour les assets statiques
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}