sonar.projectKey=rayan-tasklist-frontend
sonar.projectName=Rayan - TaskList Frontend

# URL du serveur SonarQube
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr

# Sources
sonar.sources=src

# Tests
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts,src/__tests__/**/*.e2e.test.ts

# Exclusions
sonar.exclusions=\
    node_modules/**,\
    dist/**,\
    coverage/**,\
    reports/**,\
    prisma/migrations/**,\
    **/*.config.ts,\
    **/*.config.js,\
    lib/**,\
    server.js,\
    src/lib/prisma.ts,\
    src/server.ts,\
    src/__tests__/**,\
    src/controllers/task.controller.ts


sonar.test.exclusions=\
    node_modules/**,\
    dist/**

# Couverture de tests TypeScript / JavaScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8

# Duplication
sonar.cpd.exclusions=\
    src/__tests__/**